# Generated by Django 3.2.16 on 2022-11-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('login', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=64)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=100)),
            ],
        ),
    ]
